# Generated by Django 5.0.1 on 2024-01-17 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0002_prato_categoria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prato",
            name="categoria",
        ),
    ]
