# Generated by Django 5.0.1 on 2024-01-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0005_alter_prato_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prato",
            name="foto",
            field=models.ImageField(blank=True, upload_to="fotos/%Y/%m/%d/"),
        ),
    ]
