# Generated by Django 5.0.1 on 2024-01-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0008_alter_prato_foto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Prato",
        ),
    ]
