# Generated by Django 5.0.1 on 2024-01-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=500)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("PRATOS FUNDAMENTAIS", "Pratos Fundamentais"),
                            ("CUMBUCAS", "Cumbuca"),
                            ("ENSOPADOS", "Ensopados"),
                            ("SALTEADOS", "Salteados"),
                            ("SALADAS", "Saladas"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField()),
                ("peso", models.IntegerField()),
                ("calorias", models.IntegerField()),
                ("carbo", models.IntegerField()),
                ("gorduras", models.IntegerField()),
                ("proteinas", models.IntegerField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=4)),
                ("foto", models.ImageField(blank=True, upload_to="fotos/%Y/%m/%d/")),
                ("publicado", models.BooleanField(default=False)),
            ],
        ),
    ]
