# Generated by Django 5.0.1 on 2024-01-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urucum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prato",
            name="foto",
            field=models.ImageField(blank=True, upload_to="fotos/"),
        ),
    ]
